"""Initial migration

Revision ID: f23368241c8b
Revises: 
Create Date: 2025-04-11 21:59:17.756922

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f23368241c8b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quiz_data', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moods', schema=None) as batch_op:
        batch_op.drop_column('quiz_data')

    # ### end Alembic commands ###
